# setup.ps1  -  one-shot installer for the Legion home-PC model server.
#
# Run ONCE, elevated (Right-click > Run with PowerShell as Administrator), e.g.:
#   powershell -ExecutionPolicy Bypass -File setup.ps1
#
# It will:
#   1. Pull the model with Ollama.
#   2. Bind Ollama to localhost only + set keep-alive (machine env).
#   3. Enable RTC wake timers + a sane sleep timeout (so the PC self-wakes for
#      cycles and sleeps back when you're not using it).
#   4. Open the gate port to the tailnet only (firewall).
#   5. Register the readiness sidecar to auto-start at logon.
#   6. Register RTC-wake "prime" tasks ~10 min before each cycle (11:00 & 17:00 ET).
#   7. Print the exact HOME_* env vars to set on the Legion side.
#
# Re-run any time to update times/thresholds (it replaces its own tasks). Re-run
# after a US daylight-saving change so the local wake times track 11:00/17:00 ET.

[CmdletBinding()]
param(
  [string]   $Model            = 'gpt-oss:20b',
  [int]      $GatePort         = 11435,
  [int]      $SleepTimeoutMin  = 60,    # idle minutes before the PC sleeps
  [int]      $VramThresholdMiB = 4000,  # "busy" if non-Ollama VRAM exceeds this
  [string[]] $BusyProcesses    = @(),   # "busy" if any of these processes run (names, no .exe)
  [string]   $KeepAlive        = '90m',
  # Cycle times in America/New_York (LEGION_CRON default '0 11,17 * * 1-5').
  # Wake fires 10 min earlier; change if you change LEGION_CRON.
  [string[]] $CycleTimesEt     = @('11:00','17:00'),
  [int]      $WakeLeadMin      = 10
)

$ErrorActionPreference = 'Stop'

# ---- admin check ------------------------------------------------------------
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
  ).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
if (-not $isAdmin) {
  Write-Error 'Run this elevated (PowerShell as Administrator).'; exit 1
}

$here = $PSScriptRoot
$sidecar = Join-Path $here 'readiness-sidecar.ps1'
$prime   = Join-Path $here 'prime.ps1'
$user    = "$env:USERDOMAIN\$env:USERNAME"

Write-Host "== Legion home-PC model server setup ==" -ForegroundColor Cyan

# ---- 1. pull the model ------------------------------------------------------
if (-not (Get-Command ollama -ErrorAction SilentlyContinue)) {
  Write-Error 'Ollama not found on PATH. Install from https://ollama.com/download first.'; exit 1
}
Write-Host "[1/7] Pulling $Model (this can take a while)..."
& ollama pull $Model
if ($LASTEXITCODE -ne 0) { Write-Error "ollama pull $Model failed."; exit 1 }

# ---- 2. bind Ollama to localhost + keep-alive (machine env) ------------------
Write-Host "[2/7] Setting OLLAMA_HOST=127.0.0.1:11434 and OLLAMA_KEEP_ALIVE=$KeepAlive (machine)..."
[Environment]::SetEnvironmentVariable('OLLAMA_HOST', '127.0.0.1:11434', 'Machine')
[Environment]::SetEnvironmentVariable('OLLAMA_KEEP_ALIVE', $KeepAlive, 'Machine')
Write-Host "      -> RESTART Ollama (quit the tray app and relaunch, or reboot) for this to take effect." -ForegroundColor Yellow

# ---- 3. power: wake timers + sleep timeout ----------------------------------
Write-Host "[3/7] Enabling wake timers and setting sleep timeout to $SleepTimeoutMin min..."
# "Allow wake timers" (SUB_SLEEP \ ALLOWWAKE) = 1, on AC and battery.
& powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_SLEEP BD3B718A-0680-4D9D-8AB2-E1D2B4AC806D 1
& powercfg /SETDCVALUEINDEX SCHEME_CURRENT SUB_SLEEP BD3B718A-0680-4D9D-8AB2-E1D2B4AC806D 1
& powercfg /CHANGE standby-timeout-ac $SleepTimeoutMin
& powercfg /SETACTIVE SCHEME_CURRENT
Write-Host "      Wake timers ON, sleep after $SleepTimeoutMin min idle."
Write-Host "      NOTE: keep the PC on SLEEP or HIBERNATE, never full shutdown - RTC wake cannot fire from S5." -ForegroundColor Yellow

# ---- 4. firewall: gate port from tailnet only -------------------------------
Write-Host "[4/7] Opening TCP $GatePort to the tailnet (100.64.0.0/10) only..."
$fwName = 'Legion PC sidecar (tailnet)'
Get-NetFirewallRule -DisplayName $fwName -ErrorAction SilentlyContinue | Remove-NetFirewallRule
New-NetFirewallRule -DisplayName $fwName -Direction Inbound -Action Allow `
  -Protocol TCP -LocalPort $GatePort -RemoteAddress '100.64.0.0/10' | Out-Null

# ---- 5. write config + register the sidecar at-logon ------------------------
Write-Host "[5/7] Writing config + registering the readiness sidecar (auto-start at logon)..."
$cfgLines = @(
  "# Generated by setup.ps1 on $(Get-Date -Format s). Re-run setup to change.",
  "`$script:GatePort         = $GatePort",
  "`$script:Model            = '$Model'",
  "`$script:VramThresholdMiB = $VramThresholdMiB",
  "`$script:BusyProcesses    = @($(($BusyProcesses | ForEach-Object { "'$_'" }) -join ', '))",
  "`$script:KeepAlive        = '$KeepAlive'"
)
Set-Content -Path (Join-Path $here 'legion-pc.config.ps1') -Value $cfgLines -Encoding UTF8

$psExe = "$env:WINDIR\System32\WindowsPowerShell\v1.0\powershell.exe"
function Reset-Task($name) {
  Get-ScheduledTask -TaskName $name -ErrorAction SilentlyContinue | Unregister-ScheduledTask -Confirm:$false
}

Reset-Task 'Legion Readiness Sidecar'
$sideAction  = New-ScheduledTaskAction -Execute $psExe `
  -Argument "-ExecutionPolicy Bypass -WindowStyle Hidden -File `"$sidecar`""
$sideTrigger = New-ScheduledTaskTrigger -AtLogOn -User $user
$sideSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
  -MultipleInstances IgnoreNew
$sidePrincipal = New-ScheduledTaskPrincipal -UserId $user -LogonType Interactive -RunLevel Highest
Register-ScheduledTask -TaskName 'Legion Readiness Sidecar' -Action $sideAction -Trigger $sideTrigger `
  -Settings $sideSettings -Principal $sidePrincipal | Out-Null
# start it now too
Start-ScheduledTask -TaskName 'Legion Readiness Sidecar'

# ---- 6. RTC-wake prime tasks ------------------------------------------------
Write-Host "[6/7] Registering RTC-wake prime tasks ($WakeLeadMin min before each cycle)..."
$etz = [System.TimeZoneInfo]::FindSystemTimeZoneById('Eastern Standard Time')
$primeAction = New-ScheduledTaskAction -Execute $psExe `
  -Argument "-ExecutionPolicy Bypass -WindowStyle Hidden -File `"$prime`""
$primeSettings = New-ScheduledTaskSettingsSet -WakeToRun -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries -StartWhenAvailable -MultipleInstances IgnoreNew `
  -ExecutionTimeLimit (New-TimeSpan -Minutes 15)
$primePrincipal = New-ScheduledTaskPrincipal -UserId $user -LogonType Interactive -RunLevel Limited

$today = Get-Date -Format 'yyyy-MM-dd'
$i = 0
foreach ($et in $CycleTimesEt) {
  $i++
  $etDt = [datetime]::ParseExact("$today $et", 'yyyy-MM-dd HH:mm', $null)
  $etDt = $etDt.AddMinutes(-$WakeLeadMin)
  # interpret as ET wall time -> convert to this PC's local time (handles DST at setup time)
  $utc = [System.TimeZoneInfo]::ConvertTimeToUtc([datetime]::SpecifyKind($etDt, 'Unspecified'), $etz)
  $local = [System.TimeZoneInfo]::ConvertTimeFromUtc($utc, [System.TimeZoneInfo]::Local)
  $name = "Legion Wake+Prime $i"
  Reset-Task $name
  $trigger = New-ScheduledTaskTrigger -Daily -At $local
  Register-ScheduledTask -TaskName $name -Action $primeAction -Trigger $trigger `
    -Settings $primeSettings -Principal $primePrincipal | Out-Null
  Write-Host ("      $name  ->  {0} local  (= {1} ET, cycle {2} ET)" -f $local.ToString('HH:mm'), $etDt.ToString('HH:mm'), $et)
}
Write-Host ("      One wake per cycle ({0} wakes/day, one before each cycle time)." -f $CycleTimesEt.Count) -ForegroundColor DarkGray
Write-Host "      Each recurs daily incl. weekends; prime.ps1 skips warming on US-market-closed days." -ForegroundColor DarkGray

# ---- 7. print the Legion-side env -------------------------------------------
$tsIp = ''
try { $tsIp = (& tailscale ip -4 2>$null | Select-Object -First 1).Trim() } catch { }
if (-not $tsIp) { $tsIp = '<this-PC-tailscale-ip>' }

Write-Host "`n[7/7] DONE. Set these on the Legion side (.env) and redeploy:" -ForegroundColor Green
Write-Host "      HOME_OLLAMA_URL=http://${tsIp}:${GatePort}"
Write-Host "      HOME_MODEL=$Model"
Write-Host "      HOME_THINK=true"
Write-Host "`nVerify now:" -ForegroundColor Cyan
Write-Host "      Invoke-RestMethod http://localhost:${GatePort}/ready    # this PC: should show ready=true when idle"
Write-Host "      # From the Oracle VM (on the tailnet):"
Write-Host "      curl http://${tsIp}:${GatePort}/api/tags                # should list models when idle, 503 when you're gaming"
Write-Host "`nReminder: restart Ollama (or reboot) so OLLAMA_HOST/keep-alive apply." -ForegroundColor Yellow
